### ISSUE TITLE
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'load' in ./template/base.html preventing installation

### ISSUE THREAD

**Issue by chr1s3sw0rthy** [rasulkireev/django-saas-starter#1]
Glad to find out I am doing it wrong.

Created virtual env
pip install cookiecutter
cookiecutter https://github.com/builtwithdjango/bwd-django-cookiecutter

seems to be an error in .templates/base.html. Not sure because the install failed before templates are created locally.

(env) (base) chrisesworthy@Chriss-MacBook-Pro V2 % cookiecutter https://github.com/builtwithdjango/bwd-django-cookiecutter
You've downloaded /Users/chrisesworthy/.cookiecutters/bwd-django-cookiecutter before. Is it okay to delete and re-download it? [yes]: yes
project_name [My Awesome Project]: AfterBurner V2
project_slug [afterburner_v2]: 
repo_url [https://github.com/cookiecutter/cookiecutter]: https://github.com/D-Cortex/V2.git
project_description []: AfterBurner Redaction Beta
author_name [Jane Doe]: Digital Cortex
author_email [janedoe@example.com]: chris@digital-cortex.io
Traceback (most recent call last):
  File "/Users/chrisesworthy/opt/anaconda3/bin/cookiecutter", line 10, in <module>
    sys.exit(main())
  File "/Users/chrisesworthy/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/chrisesworthy/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/chrisesworthy/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/chrisesworthy/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/chrisesworthy/opt/anaconda3/lib/python3.9/site-packages/cookiecutter/cli.py", line 140, in main
    cookiecutter(
  File "/Users/chrisesworthy/opt/anaconda3/lib/python3.9/site-packages/cookiecutter/main.py", line 101, in cookiecutter
    result = generate_files(
  File "/Users/chrisesworthy/opt/anaconda3/lib/python3.9/site-packages/cookiecutter/generate.py", line 352, in generate_files
    generate_file(
  File "/Users/chrisesworthy/opt/anaconda3/lib/python3.9/site-packages/cookiecutter/generate.py", line 169, in generate_file
    tmpl = env.get_template(infile_fwd_slashes)
  File "/Users/chrisesworthy/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/chrisesworthy/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/chrisesworthy/opt/anaconda3/lib/python3.9/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/Users/chrisesworthy/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/chrisesworthy/opt/anaconda3/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/chrisesworthy/opt/anaconda3/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "./templates/base.html", line 1, in template
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'load'.
  File "./templates/base.html", line 1
    {% load webpack_loader static %}

**Comment by rasulkireev** [comment]
Hey there Chris,

Thanks for giving my cookiecutter a try. I should have mentioned this in the README, but this is so early in the development that it would be hardly useful to anyone. It will only become useful after I write some docs for it.

I think the issue is that I don't have a `requirements.py` present. You have to use poetry right now, to install all the dependencies.

**Comment by chr1s3sw0rthy** [comment]
Not a problem. I appreciate the initiative. 

I went back to pydanny’s version for my current project. But I will watch for a more baked version and will try it. 

We need a good 4.0 cookie cutter.

**Comment by rasulkireev** [comment]
I think this is solved.
